;ACTIVIDAD 2.2. EJERCICIOS
;-------------------------
;DAVID EZEQUIEL CABALLERO GONZALEZ
;-------------------------
;LENGUAJE DE INTERFAZ
;-------------------------
;CODIGO3: CREACION DE 4 VENTANAS DE DIFERENTES COLORES CON NOMBRE
;MODIFICANDO EL CODIGO CUADRO.asm
;-------------------------
;CODIGOS UTILIZADOS
;CUADRO.asm: CODIGO BASE PARA LA CREACION DE LAS 4 VENTANAS
;COLOR1.asm: CODIGO CON LA LOGICA DE PONER UNA CADENA EN EL CENTRO DE LA VENTANA


PILA SEGMENT STACK
DB 64 DUP('PILA')
PILA ENDS

DATOS SEGMENT
    Nombre1 db 'David$'
    Nombre2 db 'Ezequiel$'
    Apellido1 db 'Caballero$'
    Apellido2 db 'Gonzalez$'
DATOS ENDS


CODIGO SEGMENT
ASSUME CS:CODIGO,SS:PILA, DS:DATOS

INICIO:

MOV AX, DATOS
MOV DS, AX

;LIMPIAR PANTALLA
MOV AX, 0600H
MOV BH, 07H
MOV CX, 0000H
MOV DX, 184FH 
INT 10H

;CUADRO 1, ESQUINA SUPERIOR IZQUIERDA
mov ax, 0600h
mov bh, 70h    
mov cx, 0101h  
mov dx, 0720h  
int 10h

;POSICIONAR CURSOR PARA NOMBRE 1 
MOV AH, 02H     
MOV BH, 00H     
MOV DX, 040DH   
INT 10H

;IMPRIMIR NOMBRE 1
MOV DX, OFFSET Nombre1
MOV AH, 09H
INT 21H   


;CUADRO 2, ESQUINA SUPERIOR DERECHA
mov ax, 0600h
mov bh, 3Dh    
mov cx, 0121h  
mov dx, 0741h  
int 10h

;POSICIONAR CURSOR PARA NOMBRE 2 
MOV AH, 02H     
MOV BH, 00H     
MOV DX, 042CH   
INT 10H

;IMPRIMIR NOMBRE 2
MOV DX, OFFSET Nombre2
MOV AH, 09H
INT 21H


;CUADRO 3, ESQUINA INFERIOR IZQUIERDA
mov ax, 0600h
mov bh, 2Bh    
mov cx, 0801h  
mov dx, 0F20h  
int 10h

;POSICIONAR CURSOR PARA APELLIDO 1 
MOV AH, 02H     
MOV BH, 00H     
MOV DX, 0C0CH  
INT 10H

;IMPRIMIR APELLIDO 1
MOV DX, OFFSET Apellido1
MOV AH, 09H
INT 21H


;CUADRO 4, ESQUINA INFERIOR DERECHA
mov ax, 0600h
mov bh, 5Ch    
mov cx, 0821h  
mov dx, 0F41h  
int 10h

;POSICIONAR CURSOR PARA APELLIDO 2 (centrado)
MOV AH, 02H     
MOV BH, 00H     
MOV DX, 0C2CH   
INT 10H

;IMPRIMIR APELLIDO 2
MOV DX, OFFSET Apellido2
MOV AH, 09H
INT 21H


;SALIDA
mov ah,1h
int 21h

mov ah, 4ch
int 21h
CODIGO ENDS
END INICIO